jenkins:
  systemMessage: "Calculator App CI — Fully automated"

  securityRealm:
    local:
      users:
        - id: "admin"
          password: "admin123"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: true

jobs:
  - script: >
      pipelineJob('calculator-app-ci') {

        description("CI/CD Pipeline with Active & Reactive Choices")

        parameters {

          activeChoiceParam('ENVIRONMENT') {
            description('Select the environment to deploy to')
            filterable()
            choiceType('SINGLE_SELECT')
            groovyScript {
              script('["dev1", "dev2", "dev3"]')
              fallbackScript('["dev1"]')
            }
          }

          activeChoiceReactiveParam('SERVER_URL') {
            description('Auto-selects localhost port based on environment')
            choiceType('SINGLE_SELECT')
            groovyScript {
              script('''
                if (ENVIRONMENT == "dev1") return ["localhost:5001"]
                if (ENVIRONMENT == "dev2") return ["localhost:5002"]
                if (ENVIRONMENT == "dev3") return ["localhost:5003"]
                return ["unknown"]
              ''')
              fallbackScript('["unknown"]')
            }
            referencedParameter('ENVIRONMENT')
          }
        }

        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/saimudunuri09/calculator_app.git')
                }
                branches('*/master')
              }
            }
            scriptPath('jenkins/Jenkinsfile')
          }
        }

        triggers {
          githubPush()
        }
      }
