pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/saimudunuri09/calculator_app.git'
            }
        }

        stage('Setup Virtual Environment') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    . venv/bin/activate
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest -v
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculator-app .'
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo "Deploying to ${ENVIRONMENT}"

                    def PORT = ""
                    def CONTAINER_NAME = ""

                    if (ENVIRONMENT == "dev1") {
                        PORT = "5001"
                        CONTAINER_NAME = "calculator-dev1"
                    }
                    else if (ENVIRONMENT == "dev2") {
                        PORT = "5002"
                        CONTAINER_NAME = "calculator-dev2"
                    }
                    else if (ENVIRONMENT == "dev3") {
                        PORT = "5003"
                        CONTAINER_NAME = "calculator-dev3"
                    }
                    else {
                        error "Invalid environment selected!"
                    }

                    sh """
                        docker stop ${CONTAINER_NAME} || true
                        docker rm ${CONTAINER_NAME} || true
                        docker run -d -p ${PORT}:5000 --name ${CONTAINER_NAME} calculator-app
                    """

                    echo "========================================="
                    echo " 🚀 DEPLOYMENT SUCCESSFUL"
                    echo "========================================="
                    echo "Environment     : ${ENVIRONMENT}"
                    echo "App Running At  : http://localhost:${PORT}"
                    echo "========================================="
                }
            }
        }
    }
}