pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/saimudunuri09/calculator_app.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt || pip3 install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest -v'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t calculator-app .'
            }
        }

        stage('Deploy') {
            steps {
                script {

                    echo "Deploying to environment: ${ENVIRONMENT}"
                    echo "Resolved Server URL: ${SERVER_URL}"

                    def ipOnly = SERVER_URL.split(":")[0]

                    sh """
                    ssh user@${ipOnly} '
                        docker stop calculator-app || true &&
                        docker rm calculator-app || true &&
                        docker run -d -p 5000:5000 --name calculator-app calculator-app
                    '
                    """

                    echo ""
                    echo "==============================================="
                    echo "   🚀 DEPLOYMENT SUCCESSFUL"
                    echo "==============================================="
                    echo "Environment     : ${ENVIRONMENT}"
                    echo "Application URL : http://${SERVER_URL}"
                    echo "==============================================="
                    echo ""
                }
            }
        }
    }
}
